"""Checks the projection is correct for navio online data. Samples points directly from voxels and draws them on bev"""
# !/usr/bin/env python3
import matplotlib
import numpy as np

matplotlib.use("Agg")
import os
import pathlib

import cv2
import matplotlib.pyplot as plt

from lib.common.box import points_in_obb
from lib.core import voxelizer
from lib.readers.pcd_reader import PCDReader

# -----------------------------
# Параметры из генератора
# -----------------------------
DYNAMIC_LABEL = 3
VOXEL_SIZE = 0.2
GRID = (0.0, -25.6, -0.8, 51.2, 25.6, 5.6)

REF_SIZE_X = 256
REF_SIZE_Y = 256


def voxelize_points_from_obbs(pc, obbs):
    """
    1) Точки → фильтр по OBB (как в генераторе)
    2) Точки → dense_map через voxelizer (как в генераторе)
    """

    # --- Собираем индексы точек внутри всех OBB ---
    all_inds = []
    for obb in obbs:
        inside = np.where(points_in_obb(pc[:, :3], obb))
        all_inds.append(inside)

    if len(all_inds) == 0:
        return None

    flat_inds = np.hstack(all_inds).flatten()
    if len(flat_inds) == 0:
        return None

    pc_sel = pc[flat_inds]

    # --- VOXELIZE ТАК ЖЕ, КАК В ГЕНЕРАТОРЕ ---
    dense_map = voxelizer.voxelize(
        pc_sel,
        np.full((pc_sel.shape[0],), fill_value=DYNAMIC_LABEL),
        voxel_size=(VOXEL_SIZE, VOXEL_SIZE, VOXEL_SIZE),
        coors_range=GRID,
        reduction="max"
    )

    return dense_map


def check_objects_from_voxels(dense_map, bev_rgb):
    """
    Семплируем координаты всех ненулевых вокселей и рисуем на BEV.
    """

    if dense_map is None:
        print("Нет вокселей машин.")
        return

    # Ненулевые воксели → координаты
    occ = np.argwhere(dense_map != 0)   # (x, y, z)

    if len(occ) == 0:
        print("Пустой dense_map — нет машин.")
        return

    xs = occ[:, 0]
    ys = occ[:, 1]

    plt.figure(figsize=(8, 8))
    plt.imshow(bev_rgb)
    plt.scatter(xs, ys, c="red", s=6, alpha=0.6, label="dynamic voxels")
    plt.legend()
    plt.title("Проверка: voxels → готовый BEV")
    plt.savefig("bev_check.png", dpi=200)
    print("Saved bev_check.png")


# ----------------------- MAIN -----------------------
if __name__ == "__main__":

    seq = "96554b64-69d4-4b50-b5cf-e26752b37eaf_kc2-139_logs_2025-10-17_16-09-08__dwn_27_10_2025_19_17_00_data"  # пример
    # idx = 0      # нужный кадр
    lidar = "frame_0000_1760708905549986304.pcd"
    detection = "frame_0000_1760708905600000000.json"
    bev = "aggregated_0.png"

    home_folder = "/downloaded_data/datasets/occupancy/autogenerated"

    lidar_path = os.path.join(home_folder, seq, "lidar", lidar)
    detects_path = os.path.join(home_folder, seq, "detects", detection)
    bev_path = f"output/bev_color/{seq}/{bev}"

    if not pathlib.Path(bev_path).exists():
        print("Нет bev картинки:", bev_path)
        exit()

    pc_reader = PCDReader()
    pc = pc_reader.read_cloud(lidar_path)
    obbs = pc_reader.get_boxes(detects_path)

    dense_map = voxelize_points_from_obbs(pc, obbs)

    bev_rgb = cv2.cvtColor(cv2.imread(bev_path), cv2.COLOR_BGR2RGB)

    check_objects_from_voxels(dense_map, bev_rgb)
