"""
Projects dynamic objects (using boxes in labels) onto bev static images
"""

import argparse
import os
import pathlib

import cv2
from tqdm import tqdm

from lib.common.data_utils import get_bev
from lib.common.label_lut import int2color_minimal, static_lut
from lib.readers.pcd_reader import PCDReader

ap = argparse.ArgumentParser()
ap.add_argument("--data_root", type=str, default="/downloaded_data/datasets/occupancy/autogenerated", help="Path to dataset with bag recordings")
args = ap.parse_args()

home_folder = args.data_root
reader = PCDReader()


for seq in tqdm(os.listdir(home_folder)):
    if not pathlib.Path(os.path.join(home_folder, seq)).is_dir():
        continue

    cloud_paths = sorted(os.listdir(os.path.join(home_folder, seq, "lidar")))
    anno_paths = sorted(os.listdir(os.path.join(home_folder, seq, "detects")))
    agg_static_paths = sorted(os.listdir(os.path.join(home_folder, seq, "agg_static")))
    frame_static_paths = sorted(os.listdir(os.path.join(home_folder, seq, "static")))
    blind_zones = sorted(os.listdir(os.path.join(home_folder, seq, "blind_zones")))

    save_dir_color = os.path.join(home_folder, seq, "bev_color")
    pathlib.Path(save_dir_color).mkdir(exist_ok=True, parents=True)
    save_dir = os.path.join(home_folder, seq, "bev")
    pathlib.Path(save_dir).mkdir(exist_ok=True, parents=True)

    for i, _ in enumerate(agg_static_paths):
        cloud_path = os.path.join(home_folder, seq, "lidar", cloud_paths[i])
        anno_path = os.path.join(home_folder, seq, "detects", anno_paths[i])
        agg_static_path = os.path.join(home_folder, seq, "agg_static", agg_static_paths[i])
        frame_static_path = os.path.join(home_folder, seq, "static", frame_static_paths[i])
        blind_zone_path = os.path.join(home_folder, seq, "blind_zones", blind_zones[i])

        bev_color, bev_label, static_color, static_label = get_bev(reader, cloud_path, anno_path, agg_static_path, frame_static_path, blind_zone_path, static_lut, int2color_minimal)

        fname = cloud_paths[i].split(".")[0]
        cv2.imwrite(os.path.join(save_dir_color, f"{fname}.png"), bev_color)
        cv2.imwrite(os.path.join(save_dir, f"{fname}.png"), bev_label)

        # Сохраняем для меньших масштабов
        scales = [2, 4, 8]
        orig_size = bev_label.shape
        for scale in scales:
            save_path = str(save_dir / f"{fname}_1_{scale}.png")
            bev_scaled = cv2.resize(bev_label, (orig_size[0] // scale, orig_size[1] // scale), interpolation=cv2.INTER_NEAREST)
            cv2.imwrite(save_path, bev_scaled)
